### ISSUE TITLE
Can't connect to model

### ISSUE THREAD

**Issue by piavgh** [jeteokeeffe/php-hmac-rest-api#14]
Hi everyone,

I've tried to get some record from database, here what I did

1. Replace parameters in config.php with my database connection
2. Create class Princess.php in models folder (suppose I have a "princesses" table in database)
<pre><code>
<?php 
namespace Models;
class Princess extends \Phalcon\Mvc\Model {
	public function getSource(){
		return "princesses";
	}
}
</code></pre>
3. Create class PrincessController.php in controllers folder
<pre><code>
<?php
namespace Controllers;
class PrincessController extends \Phalcon\Mvc\Controller {
	public function princessAction() {
		$data = array();
		$princesses = Princess::find();
		foreach ($princesses as $princess) {
			$data[] = $princess->name;
		}
		echo json_encode($data);
	}
}
</code></pre>
4. Add to routes.php
<pre><code>$routes[] = [
	'method' => 'get', 
	'route' => '/princess', 
	'handler' => ['Controllers\PrincessController', 'princessAction'],
	'authentication' => FALSE
];</code></pre>
5. Open browser and go to localhost/princess (localhost is just an example for url, I've tested this on real server which satisfied all requirements) and I get blank page
6. I checked error.log in /var/log/nginx/error.log (I use Nginx web server) and what I get is <pre><code>"PHP Fatal Error: Class 'Controllers\Princess' not found in ....</code></pre>

Do you know what wrong with my implementation?

Thank you very much

**EDIT**

I've copied the Princess.php class from models to controllers folder, and replace "namespace Models" with "namespace Controllers", and everything is fine, I can get all records from database. But I think it's not right, because Princess.php is model, not controller

**EDIT 2**
I added this in PrincessController.php file <pre><code>use \Models\Princess as Princess;</code></pre> and now it's right.

Suggestion: Is there anyway that I can use Conventions like the Phalcon MVC example INVO? I mean the controller automatically find the model, no need to use that line?

**Comment by jeteokeeffe** [comment]
I could completely move it away from namespaces and just do autoloading by directory but I don't think that is as dynamic, flexible approach. What if you have 2 classes named Princess (one a model and the other completely different)? Namespaces support that type of functionality and in my opinion, are a best practice.

**Comment by piavgh** [comment]
Thank you very much, I'm new to Phalcon. I've just read the Autoloader part in the document and yes, I also think Namespaces is the most dynamic way to code

**Comment by jeteokeeffe** [comment]
No worries, I hope project works for you
