### ISSUE TITLE
Support versioning?

### ISSUE THREAD

**Issue by piavgh** [jeteokeeffe/php-hmac-rest-api#15]
Hi jeteokeeffe,

Do you think about support versioning in your repo? I mean something like api.example.com/v1/example.
Just want to know your opinion.

https://github.com/cmoore4/phalcon-rest did it pretty good, followed best practice in API design https://blog.apigee.com/detail/announcement_new_ebook_on_web_api_design

Thank you

**Comment by jeteokeeffe** [comment]
I just looked over https://github.com/cmoore4/phalcon-rest and he did a great job. I went a little more bare bones (mine is more of a phalcon micro bootstrap). That said, you can create versioning with my project.

For example, in php-hmac-rest-api/app/config/routes.php
```php
$routes[] = [ 
    'method' => 'put',
    'route' => '/v1/schedule/{eventId}',
    'handler' => ['Controllers\ScheduleController', 'updateAction']
];
```

Example controller
```php
namespace Controllers;
class ScheduleController extends \Phalcon\Mvc\Controller {
public function updateAction($eventId) {
```

**Comment by jeteokeeffe** [comment]
did that answer your question? does that example work?

```php
$routes[] = [ 
    'method' => 'put',
    'route' => '/v1/schedule/{eventId}',
    'handler' => ['Controllers\ScheduleController', 'updateAction']
];
$routes[] = [ 
    'method' => 'put',
    'route' => '/v2/schedule/{eventId}',
    'handler' => ['Controllers\ScheduleController', 'newUpdateAction']
];
```

```php
namespace Controllers;
class ScheduleController extends \Phalcon\Mvc\Controller {
public function updateAction($eventId) {
}

public function newUpdateAction($eventId) {
}
}
```

**Comment by piavgh** [comment]
Yes, I thought about something like 'route' => '/v1/schedule'/...' before, but suppose if you have about 1000 routes in your api, and you decide to upgrade to 'v2'. Now you have to change 1000 'v1' to 'v2' in you routes.php, or at least use "Replace All" function of text editor :D.

You did a great job with the way you handle routes, it's more flexible, but is there anyway to change in only 1 place, and it apply in every routes like cmoore4 did

<pre><code>
$exampleCollection
		// VERSION NUMBER SHOULD BE FIRST URL PARAMETER, ALWAYS
		->setPrefix('/v1/example')
		// Must be a string in order to support lazy loading
		->setHandler('\PhalconRest\Controllers\ExampleController')
		->setLazy(true);
</code></pre>

Thank you very much.

**Comment by jeteokeeffe** [comment]
Alot of different ways to go here.

Option 1: Allow user to set version, then add logic in controller to handle version (ensure user stays honest)

```php
$routes[] = [ 
    'method' => 'put',
    'route' => '/{version}/schedule/{eventId}',
    'handler' => ['Controllers\ScheduleController', 'updateAction']
];

namespace Controllers;
class ScheduleController extends \Phalcon\Mvc\Controller {
public function updateAction($version, $eventId) {
}
```

Option 2: Modify setRoutes method in `app/library/application/Micro.php` to use collections

```php
$routes[] = [
        'prefix' => '/v1',
	'method' => 'post', 
	'route' => '/ping', 
	'handler' => ['Controllers\ExampleController', 'pingAction']
];
```
```php

foreach($routes as $obj) {
$collection
        ->setPrefix($prefix)
        // Must be a string in order to support lazy loading
        ->setHandler($handler)
        ->setLazy(true);

switch($method) {
  case 'post':
    $collection->post($route);
  case .... # you get the point
}
$this->mount($exampleCollection);
}
```

I haven't worked much with collections, so I'd have to make sure you can mount multiple collections. Pros and cons for each way ....

**Comment by piavgh** [comment]
Thank you very much. I'll try to follow Option 2 :)
