### ISSUE TITLE
How to call a dependency injection from controller?

### ISSUE THREAD

**Issue by piavgh** [jeteokeeffe/php-hmac-rest-api#16]
Hi jete,

For example, in setConfig function in Micro.php, I set

<pre><code>
$di->set('security', function(){

		    $security = new Phalcon\Security();

		    //Set the password hashing factor to 12 rounds
		    $security->setWorkFactor(12);

		    return $security;
		}, true);

		$this->setDI($di);
</code></pre>

How can I call 'security' from my controller? 
I have this function in ExampleController

<pre><code>
public function genpassAction($password) {
		$response = new \Phalcon\Http\Response();
		$security = $di->get("security");
		$password_hash = $security->hash($password);
		
		$response->setStatusCode(200, "OK");
		$response->setJsonContent(array('status' => 'OK', 'data' => $password_hash));

		$response->setHeader('Access-Control-Allow-Origin', '*');
    	$response->sendHeaders();

    	return $response;
	}
</code></pre>

I take a look at error.log and this line <pre><code>$security = $di->get("security");</code></pre> cause error.
Even if I delete that line above and replace <pre><code>$password_hash = $security->hash($password);</code></pre> with <pre><code>$password_hash = $app->security->hash($password);</code></pre>, I still got the similar error

If I follow the Micro tutorial of Phalcon, I can do this
<pre><code>$app->get('/api/user/genPass/{password}', function($password) use ($app) {</code></pre>

but now I don't know how to "use ($app)" with your code

Can you show me how?

Thank you very much

**Comment by jeteokeeffe** [comment]
hey, sorry, missed this post. do you still need help?

**Comment by piavgh** [comment]
Hi,

I've found a way to solve this problem, in Phalcon doc they call "Accessing the DI in a static way" :D 

$request = \Phalcon\DI::getDefault()->getRequest();

But I wonder is there any "more dynamic" way?

Thank you
