### ISSUE TITLE
Upgrade required for Phalcon 2.0?

### ISSUE THREAD

**Issue by mizterp** [jeteokeeffe/php-hmac-rest-api#18]
Could you please confirm if your PHP HMAC Restful API requires any updates to be 100% compatible with Phalcon 2.0 ?

**Comment by jeteokeeffe** [comment]
idk, ill have to test it out. i didnt know phalcon 2 was out until you posted this, lol

**Comment by jeteokeeffe** [comment]
according to the phalcon forum, code that is 1.3 compliant will work fine w/ 2.0.
http://forum.phalconphp.com/discussion/3381/phalcon-2-0-or-1-3-

**Comment by mizterp** [comment]
Cool, thanks for looking into it!
