### ISSUE TITLE
404 /ping not found

### ISSUE THREAD

**Issue by himanshukpatel** [jeteokeeffe/php-hmac-rest-api#22]
Request: POST /playtcher/ping HTTP/1.1 Host: localhost Accept: */* API_ID: 1 API_TIME: 1444593417 API_HASH: 45263f4dc092b420c59792066aa6603a82845a11279034f1534acd2a8ef15e19 Content-Length: 142 Expect: 100-continue Content-Type: multipart/form-data; boundary=------------------------234e896c0f8251d7 Response: HTTP/1.1 100 Continue HTTP/1.1 404 Not Found Date: Sun, 11 Oct 2015 19:56:57 GMT Server: Apache/2.4.9 (Win64) PHP/5.5.12 Content-Length: 296 Content-Type: text/html; charset=iso-8859-1
Not Found

The requested URL /playtcher/ping was not found on this server.

Apache/2.4.9 (Win64) PHP/5.5.12 Server at localhost Port 80

**Comment by himanshukpatel** [comment]
CAN ANYBODY EXPLAIN ME WHY THIS IS HAPPENING. ?????

**Comment by jeteokeeffe** [comment]
can you post your vhost configuration or .htacess file since you're using apache.

**Comment by himanshukpatel** [comment]
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule  ^$ public/    [L]
    RewriteRule  (.*) public/$1 [L]
</IfModule>

**Comment by himanshukpatel** [comment]
i have placed .htaccess in root folder. but i got 500 internal server error..
i dont have any idea why this is happening

**Comment by himanshukpatel** [comment]
can anybody help me to solve this issue as soon as possible.

**Comment by Lomion-tm** [comment]
Did you try the Setup + Tutorials on phalconphp.com? https://docs.phalconphp.com/en/latest/reference/apache.html
The part starting with "Directory under the main Document Root" might be interesting for you! I think your setup is somewhat messed up.

**Comment by himanshukpatel** [comment]
i have already setup that. i have another phalcon project running fine. but in this might be something else.

**Comment by jeteokeeffe** [comment]
Request: POST /playtcher/ping HTTP/1.1 Host: localhost Accept: / API_ID: 1 API_TIME: 1444593417 API_HASH: 45263f4dc092b420c59792066aa6603a82845a11279034f1534acd2a8ef15e19 Content-Length: 142 Expect: 100-continue Content-Type: multipart/form-data; boundary=------------------------234e896c0f8251d7 Response: HTTP/1.1 100 Continue HTTP/1.1 404 Not Found Date: Sun, 11 Oct 2015 19:56:57 GMT Server: Apache/2.4.9 (Win64) PHP/5.5.12 Content-Length: 296 Content-Type: text/html; charset=iso-8859-1
Not Found


Uhmm, the request should just go to /ping and not /playtcher/ping. Your doc root is a problem.

**Comment by himanshukpatel** [comment]
Request: POST /ping HTTP/1.1 Host: localhost Accept: */* API_ID: 1 API_TIME: 1444668127 API_HASH: 16a877840587505a3287d70703b89422566fa6ecdeede26436ce4deabcced737 Content-Length: 142 Expect: 100-continue Content-Type: multipart/form-data; boundary=------------------------843754d30c9724a3 Response: HTTP/1.1 100 Continue HTTP/1.1 404 Not Found Date: Mon, 12 Oct 2015 16:42:08 GMT Server: Apache/2.4.9 (Win64) PHP/5.5.12 Content-Length: 286 Content-Type: text/html; charset=iso-8859-1
Not Found

The requested URL /ping was not found on this server.

Apache/2.4.9 (Win64) PHP/5.5.12 Server at localhost Port 80

**Comment by himanshukpatel** [comment]
still i got this error

**Comment by himanshukpatel** [comment]
my project path is c:\wamp\www\hmac\


-------------------------
this is request 

$route = '/ping';
//$route = '/test/4';
//$route = '/doesntexist';
//$route = '/skip/auth';

if (isset($argv[1])) {
	$host = 'http://' . $argv[1] . $route;
} else {
	$host = "http://localhost" . $route;
}

**Comment by jeteokeeffe** [comment]
My recommendation is to get it working w/ php built in web server.

cd php-hmac-rest-api/public
php -S localhost:8000 ../.htrouter.php

If that works, you know its your apache setup.

**Comment by himanshukpatel** [comment]
Request: POST /playtcher/ping HTTP/1.1 Host: localhost Accept: */* API_ID: 1 API_TIME: 1444669570 API_HASH: 98d5245b6d4f2c6a225fceb92593dbb9b00f0cc79f6d3ce09488307f36262284 Content-Length: 142 Expect: 100-continue Content-Type: multipart/form-data; boundary=------------------------55dd1591fcac1dde Response: HTTP/1.1 100 Continue HTTP/1.1 404 Not Found Date: Mon, 12 Oct 2015 17:06:10 GMT Server: Apache/2.4.9 (Win64) PHP/5.5.12 X-Powered-By: PHP/5.5.12 Status: 404 Not Found Content-Length: 19 Content-Type: text/html Page doesn't exist.


now i got page doest exist..

**Comment by jeteokeeffe** [comment]
POST /playtcher/ping HTTP/1.1 
shouldn't happen 

POST /ping HTTP/1.1 
it should be the proper way to request the resource

**Comment by Lomion-tm** [comment]
if (isset($argv[1])) {
	$host = 'localhost' . $argv[1] . $route;
} else {
	$host = "localhost" . $route;
}

client-connect.php -> did you change lines 13 and following according to your local setup?

**Comment by himanshukpatel** [comment]
@Lomion-tm yes i have already done that

**Comment by Lomion-tm** [comment]
Thing is your POST request should go to /ping like this:
Request: 
POST /ping HTTP/1.1
Host: nucmainbrain
Accept: */*
X-API-ID: 1
X-API-TIME: 1444728116
X-API-HASH: e78fa595d3c50174de27befe8bc94b130c41ecee6463a2a799a13ed6940b3087
Content-Length: 142
Expect: 100-continue
Content-Type: multipart/form-data; boundary=------------------------4f3260d40ff53c30

but it goes to your playtcher folder ... and then action ping. But that does not exist ... you messed up something in the client-connect.php

**Comment by himanshukpatel** [comment]
@Lomion-tm  i have phalcon with nginx installed. when i try to run public its gives me page doest not exist. 
i still got the same error page not found.
am i missing here or what. 
can you please explain me how to do step it up from scartch.
i will reinstall whole thing.

**Comment by himanshukpatel** [comment]
thanks you so me i have resolved it.
